[package]
name = "real-fast"
version = "0.8.0"
authors = ["Spencer Vess <spencervess@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
tokio = { version = "0.2", features = ["macros", "signal"] }
reqwest = { version = "0.10", features = ["rustls-tls"], default-features = false }
tempfile = "3.1"

[dependencies.serenity]
version = "0.9.0-rc.2"
default-features = false
features = [
    "cache",
    "framework",
    "standard_framework",
    "rustls_backend",
    "client",
    "builder",
    "gateway",
    "model",
    "utils",
    "absolute_ratelimits",
    "collector",
]
